name: Code Coverage Comparison

on: [ pull_request ]

# Default to bash
defaults:
  run:
    shell: bash

env:
  NODE_VERSION: 23.x

jobs:
  base_branch_cov:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Run test coverage
        run: npm run coverage --if-present

      - name: Run jest (coverage fallback)
        run: "[[ ! -f ./coverage/lcov.info ]] && npm run jest || true"

      - name: Run test (coverage fallback)
        run: "[[ ! -f ./coverage/lcov.info ]] && npm run test || true"

      - name: Upload code coverage for ref branch
        uses: actions/upload-artifact@v4
        with:
          name: ref-lcov.info
          path: ./coverage/lcov.info

  checks:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: base_branch_cov
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Download code coverage report from base branch
        uses: actions/download-artifact@v4
        with:
          name: ref-lcov.info

      - name: Install dependencies
        run: npm ci

      - name: Run test coverage
        run: npm run coverage

      #  Compares two code coverage files and generates a report as a comment
      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "./coverage/lcov.info"
          base-lcov-file: "lcov.info"
          minimum-ratio: 0 # Fails GitHub action once code coverage is decreasing
          send-summary-comment: true
          show-annotations: "warning" # Possible options warning|error
